version: '3.3'

services:
   db:
     image: mariadb:10.3
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD_FILE: /run/secrets/db_password
     secrets:
       - db_root_password
       - db_password

   wordpress:
     depends_on:
       - db
     image: wordpress:5.5.3
     volumes:
       - "./deploy/wp-content/themes/twentytwenty-child:/var/www/html/wp-content/themes/twentytwenty-child"
#       - "./deploy/wp-content/plugins:/var/www/html/wp-content/plugins"  # Update as needed...
     ports:
       - "8000:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
       WORDPRESS_DB_NAME: wordpress
     secrets:
       - db_password

volumes:
    db_data: {}

secrets:
    db_password:
      file: secrets/db_password.txt
    db_root_password:
      file: secrets/db_root_password.txt
